version: '3.8'
services:
  frontend:
    build:
      context: D:/Healthcare/Github/FE/Mediapp/
    ports:
      - "3002:3000"
    depends_on:
      - backend
  backend:
    build:
      context: D:/Healthcare/Github/BE/Auth-service/Mediapp/
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/health-care
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health-care
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
